### ISSUE TITLE
Cannot assign retweeID; exception message: Cannot read property 'id_str' 

### ISSUE THREAD

**Issue by DaveBryantLU** [spences10/twitter-bot-playground#25]
Getting all the way through to the end, hitting npm start and receiving "Cannot assign retweeID; exception message: Cannot read property 'id_str' of undefined" Would you have any idea on this as I'm stuck!

**Comment by spences10** [comment]
Hey @DaveBryantLU thanks for the feedback 👍 

Do you have an example of where you have got to? I'm assuming you have successfully set up a bot and can send a basic tweet with the bot, right?

I'm also going to assume that you now have a basic tweet bot set up, is it using search or stream API?

Thanks

**Comment by DaveBryantLU** [comment]
Hey Scott,

I followed the latest README on this after starting from scratch, I've ran
through the steps in order and reached the last part where we attempt to
retweet for the first time which is when I get the error.

Can you have a look here https://ide.c9.io/davebryantlu/twitter-bot-db when
you're free to see if I've done something incorrectly ?

All the best

[image: LearnUpon]
David Bryant
Account Manager

Email:
david@learnupon.com

Phone:

+61 283 111 209 <+61283111209>

Web:
www.learnupon.com

Twitter:

@learnupon <https://twitter.com/learnupon>

Discover why customers love LearnUpon <https://www.learnupon.com/customers/>
.

**Comment by spences10** [comment]
That's a 404 @DaveBryantLU you'll probably need to enable sharing options

![image](https://user-images.githubusercontent.com/234708/30530041-368ee2f6-9c3b-11e7-8e47-427a3e5f4a48.png)

**Comment by DaveBryantLU** [comment]
Just enabled, sorry about that!


[image: LearnUpon]
David Bryant
Account Manager

Email:
david@learnupon.com

Phone:

+61 283 111 209 <+61283111209>

Web:
www.learnupon.com

Twitter:

@learnupon <https://twitter.com/learnupon>

Discover why customers love LearnUpon <https://www.learnupon.com/customers/>
.

**Comment by spences10** [comment]
Couple of things @DaveBryantLU 

It appears that the repo in the c9 example linked is the bootstrap example, not the playground, if that's the case this can be closed and moved to the https://github.com/spences10/twitter-bot-bootstrap repo

There is no terminal access on the c9 environment linked so all I can do is look at the code, it appears that all that has changed is the addition of a `.env` file if you could enable me to run the code I can get a better idea of where the issue may be

Thanks

**Comment by DaveBryantLU** [comment]
Got it working, changing lang/language to lan in the config and .env did
the trick.

Just wondering, are you aware of how to limit the search function to
specific accounts only, i:e @Youtube for instance ?

Cheers


[image: LearnUpon]
David Bryant
Account Manager

Email:
david@learnupon.com

Phone:

+61 283 111 209 <+61283111209>

Web:
www.learnupon.com

Twitter:

@learnupon <https://twitter.com/learnupon>

Discover why customers love LearnUpon <https://www.learnupon.com/customers/>
.

**Comment by spences10** [comment]
Thanks, closing, refer to the issue on the relevant repo for detail on using a blacklist

Thanks
